### ISSUE TITLE
登陆密码错误

### ISSUE THREAD

**Issue by 8October8** [vidar-team/Cardinal#101]
按照安装提示运行成功后，登陆时提示密码错误，密码我是复制过来的，不可能错，求解。
设置的比赛时间是我测试的，是明年的时间，是不是和这个有关。

**Comment by wuhan005** [comment]
请确认您访问的路由是管理端 http://localhost:19999/manager，而不是&nbsp;http://localhost:19999/

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 8October8 <notifications@github.com&gt;
发送时间: 2020年12月27日 17:08
收件人: vidar-team/Cardinal <Cardinal@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[vidar-team/Cardinal] 登陆密码错误 (#101)
