### ISSUE TITLE
【数据库连接】数据库连接用户需要什么指定要求、指定权限？

### ISSUE THREAD

**Issue by Ensuperb** [vidar-team/Cardinal#104]
![image](https://user-images.githubusercontent.com/49173457/104934200-d1ab1d80-59e4-11eb-8fd8-0685b4a8002d.png)
![image](https://user-images.githubusercontent.com/49173457/104934323-f4d5cd00-59e4-11eb-9a27-c0d9d2b5ca7a.png)

如上图，运维已经给予数据库用户SELECT, INSERT, UPDATE, DELETE, CREATE在project上的权限。

**Comment by wuhan005** [comment]
上图报错信息中，已经显示缺少`INDEX`索引权限。
请尝试赋予数据库用户`INDEX`权限。

**Comment by Ensuperb** [comment]
神速啊，👍，刚刚发现了error 1142，差个alter权限，正在解决

**Comment by Ensuperb** [comment]
创建了中文字符集的数据库，
创建了专属用户，
给予该专属用户 SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER权限。
问题已解决。

谢谢库主的及时回复与帮助。
