### ISSUE TITLE
Default language for web interface

### ISSUE THREAD

**Issue by Roooodie** [vidar-team/Cardinal#107]
Can we change the default language in the web interface for the client (player), management side and also for the Asteroid?

The default language is on Chinese language and i cannot find how to change the default language to English. 
I still can change the language into English with the button in the web interface but it wil changed again back to chinese after page closed. 
i think it's a good thing if we can choose English language for the web interface default language during the installation or under management side.
And also it's not fully English translated, like the button (`/manager/#/gamebox`, `/manager/#/config`, `/manager/#/flag`) and log at the `/manager/#/` is still in Chinese.

I hope with this feature, Cardinal can become the first choice framework to use to when someone want to try AWD or A/D and make it getting known even further.
Thanks beforehand (●'◡'●)

**Comment by wuhan005** [comment]
Thanks your feedback! 

This feature will be added in the next version.

**Comment by wuhan005** [comment]
Feature added in [version 0.7.3](https://github.com/vidar-team/Cardinal/releases/tag/v0.7.3).

Now you can set the default language to English in the manager interface: `/manager/#/config`

**Comment by Roooodie** [comment]
Thank You for the update!
but still found some character that not yet changed.

The Log in the Dashboard tab` /manager/#/ `still in chinese language, even when the language changed into english.

![image](https://user-images.githubusercontent.com/50097679/106554187-d7147600-6555-11eb-948c-77816a3c350d.png)

and also in the first instalation section, also still in chinese. it's for input system username and system password.

![image](https://user-images.githubusercontent.com/50097679/106554484-733e7d00-6556-11eb-979b-1963e2dbbfe6.png)
