### ISSUE TITLE
docker里面管理后台的密码

### ISSUE THREAD

**Issue by Mitooooo** [vidar-team/Cardinal#109]
**运行环境 Environment**:
    linux
  - 操作系统 / Operating System: 
ubuntu
**发生了什么？/ What happened?**
我不知道如何更改docker里面管理后台的密码

**Comment by wuhan005** [comment]
使用 Docker 部署与直接二进制文件启动更改管理员密码是一样的。
只是从 Docker 启动时初始密码会输出至容器的 log 中。

使用初始密码登录管理员后台，点击`账号管理`菜单，再点击对应用户旁的`修改密码`即可。

**Comment by Mitooooo** [comment]
好 谢谢
