### ISSUE TITLE
是否有计划使用codeql进行安全性扫描

### ISSUE THREAD

**Issue by LuckyC4t** [vidar-team/Cardinal#112]
作为一个AWD平台，免不了会遭受攻击，人工代码审计费时费力，是否有考虑将codeql接入github action进行扫描

**Comment by wuhan005** [comment]
嗯，可以的。
@vidar-team 组织下已经开通了 GitHub CodeQL 功能。

**Comment by wuhan005** [comment]
已加入 https://github.com/vidar-team/Cardinal/pull/113
感谢！
