### ISSUE TITLE
关于实时更新分数信息的需求

### ISSUE THREAD

**Issue by suanve** [vidar-team/Cardinal#126]
首先感谢vidar-team为广大安全人员提供了优秀的开源项目。

我在本地做二开时发现更新分数的逻辑是回合结束后计算，这里我有一点小困惑。
回合结束时记分应该只计算本轮check均分的分数，为什么把实时攻击的得分扣分的逻辑也放在回合结束呢？
是有技术难点还是什么其他的原因？（我现在在改这一部分 改的有点头大

**Comment by wuhan005** [comment]
是因为比赛规则是：每一轮结束后，被攻击方将扣分，而攻击方将平分该被攻击靶机的分数，所以需要到每轮结束后，根据攻击情况具体结算，平分分数。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Su ***@***.***&gt;
发送时间: 2021年5月25日 21:35
收件人: vidar-team/Cardinal ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[vidar-team/Cardinal] 关于实时更新分数信息的需求 (#126)





 
首先感谢vidar-team为广大安全人员提供了优秀的开源项目。
 
我在本地做二开时发现更新分数的逻辑是回合结束后计算，这里我有一点小困惑。
 回合结束时记分应该只计算本轮check均分的分数，为什么把实时攻击的得分扣分的逻辑也放在回合结束呢？
 是有技术难点还是什么其他的原因？（我现在在改这一部分 改的有点头大

**Comment by suanve** [comment]
awd分数计算，不是实时+-分然后回合结束时check通过的队伍均分check没过队伍的分么？

**Comment by suanve** [comment]
规则，攻击得50 被攻击扣50 check没过扣100

第一轮开始时分数：
a 1000
b 1000
c 1000

a攻击b并删除b的页面 导致bcheck没过
此时分数：
a 1050
b 950
c 1000

回合结束时分数：
a 1100
b 850
c 1050

**Comment by wuhan005** [comment]
根据以往我们举办比赛以及参加的 AWD 比赛，攻击得分并不是实时结算的，具体规则可以见 Cardinal 文档：https://cardinal.ink/guide/rules.html



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Su ***@***.***&gt;
发送时间: 2021年5月25日 21:47
收件人: vidar-team/Cardinal ***@***.***&gt;
抄送: E99p1ant ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[vidar-team/Cardinal] 关于实时更新分数信息的需求 (#126)
