### ISSUE TITLE
flag管理页面无法筛选10轮之后的flag

### ISSUE THREAD

**Issue by AFKL-CUIT** [vidar-team/Cardinal#129]
**运行环境 Environment**:
    
  - 操作系统 / Operating System: Linux sycsec-PowerEdge-T630 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  - 环境配置：直接使用的Releases里的0.7.2版本。mysql由docker启动，版本8.0.25。
  - 浏览器：firefox 88.0.1 (64 位)

**发生了什么？/ What happened?**
在`/manager/#/flag`页面里，填写筛选的轮数时，当填写10以上的数字时，前端会把这个数字强制变为10。

**您的预期结果是什么？/ What did you expect to happen?**
可以查询10轮以上的flag。

**Comment by wuhan005** [comment]
Fixed in https://github.com/vidar-team/Cardinal_manager_frontend/commit/1a975ab9d102aa32d218a6a478ae1b112b29c907
