### ISSUE TITLE
题目清除后，队伍题目依然存在

### ISSUE THREAD

**Issue by AFKL-CUIT** [vidar-team/Cardinal#130]
**运行环境 Environment**:
    
  - 操作系统 / Operating System: Linux sycsec-PowerEdge-T630 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  - 环境配置：直接使用的Releases里的0.7.2版本。mysql由docker启动，版本8.0.25。
  - 浏览器：firefox 88.0.1 (64 位)

**发生了什么？/ What happened?**
管理后台创建题目、分配靶机、设置可见后。将题目删除，管理后端的题目与靶机成功删除。但参赛队伍页面上的题目和分数还没有消失。（PS：幽灵题目）
只有重新发布新的题目后，这个幽灵题目才会消失。

**您的预期结果是什么？/ What did you expect to happen?**
删除题目后，管理后端和队伍的页面都没有这个题目，并扣除这个题目的分数。

**Comment by wuhan005** [comment]
一般来说，在真正的比赛过程中，很少有将题目全部删除再不上线的操作。若题目需要下线维护，可将题目状态设置为不可见，此时将更新队伍页面并重新计算分数与排行榜。
若直接删除题目，分数与排行榜将在下一轮开始时或平台重启时自动算分后更新，确实不会立刻刷新。
不知道你对这样的解释是否满意？因为这个功能我觉得将题目设置为不可见就可以做到，同时还能随时恢复。😄

**Comment by AFKL-CUIT** [comment]
> 
> 
> 一般来说，在真正的比赛过程中，很少有将题目全部删除再不上线的操作。若题目需要下线维护，可将题目状态设置为不可见，此时将更新队伍页面并重新计算分数与排行榜。
> 若直接删除题目，分数与排行榜将在下一轮开始时或平台重启时自动算分后更新，确实不会立刻刷新。
> 不知道你对这样的解释是否满意？因为这个功能我觉得将题目设置为不可见就可以做到，同时还能随时恢复。😄

确实没想到这点，是我草率了。感谢解答。
