### ISSUE TITLE
yaml文件格式问题导致编译失败

### ISSUE THREAD

**Issue by voidzhakul** [vidar-team/Cardinal#139]
![image](https://user-images.githubusercontent.com/37470928/121285763-7c2ec900-c911-11eb-8757-37ed3d7f53cc.png)

文件 `Cardinal/locales/zh-CN.yml`132行尾部存在特殊字符，会导致编译失败

**Comment by wuhan005** [comment]
感谢！已修复 https://github.com/vidar-team/Cardinal/commit/5d8032312de96ca47105bafe6fc421dde0284700
