### ISSUE TITLE
提交靶机flag一直提示flag错误

### ISSUE THREAD

**Issue by jiaocoll** [vidar-team/Cardinal#140]
**运行环境 Environment**:
    
  - 操作系统 / Operating System: 

**发生了什么？/ What happened?**

**您的预期结果是什么？/ What did you expect to happen?**

**如何复现您的问题？/ How to reproduce your issue?**

**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**

**Comment by wuhan005** [comment]
请按 issue 模板详细说明问题。
