### ISSUE TITLE
Docker场景部署下，无法获取密码

### ISSUE THREAD

**Issue by runshine** [vidar-team/Cardinal#175]
**运行环境 Environment**:
    
  - 操作系统 / Operating System: 

**发生了什么？/ What happened?**

使用curl https://sh.cardinal.ink | bash，命令执行部署，在docker的日志中没有显示密码
使用的命令为docker logs $(CONTAINER_ID)，在容器里面也未能找到密码

**您的预期结果是什么？/ What did you expect to happen?**

**如何复现您的问题？/ How to reproduce your issue?**

**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**

**Comment by wuhan005** [comment]
Cardinal 容器 docker logs 日志的最前面是有密码的。
如果没有找到，能麻烦您那边截个图看下嘛？

**Comment by runshine** [comment]
我的锅，没有删除本地挂载的数据库，导致使用的是以前的数据库，所有没有再次初始化，显示密码。
