### ISSUE TITLE
大佬帮帮我

### ISSUE THREAD

**Issue by uaxuan** [vidar-team/Cardinal#187]
**运行环境 Environment**:
    
  - 操作系统 / Operating System: 
ubuntu
**发生了什么？/ What happened?**
我新建了一个队伍，在靶机哪里也为队伍设置了题目，可是队伍进去还是看不到题目
**您的预期结果是什么？/ What did you expect to happen?**
添加完队伍和靶机后可以看到
**如何复现您的问题？/ How to reproduce your issue?**

**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**

**Comment by wuhan005** [comment]
请检查是否已为队伍创建了题目**靶机**

**Comment by uaxuan** [comment]
![LWYQ3K9{SAY~Y){62V1E1DJ](https://user-images.githubusercontent.com/83015602/189884268-e826d8b8-3f83-440c-9a21-95e2aa9f4adc.png)
就像这样

**Comment by uaxuan** [comment]
emmm
对不起
是我太笨了，题目没有设置为公开，谢谢大佬
