### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by catsay217994** [vidar-team/Cardinal#23]
我分别下载了windows版本和linux版本 在linux版本上编译失败后选择使用二进制程序同样无法运行，在windows上弹出让我选择中文或者英文，但是输入1或者2后还是循环让我输入

**Comment by wuhan005** [comment]
现已经修复并发布新版本：[v0.0.3-beta](https://github.com/vidar-team/Cardinal/releases/tag/v0.0.3-beta)

感谢您的反馈与支持！ (･ω･)ﾉ
