### ISSUE TITLE
几个使用小问题

### ISSUE THREAD

**Issue by XuCcc** [vidar-team/Cardinal#26]
1. 经常有这个错

```sh
(/home/github.com/vidar-team/Cardinal/src/log.go:27)
[2020-04-14 15:22:01]  Error 1366: Incorrect string value: '\xE7\xAC\xAC 29...' for column 'content' at row 1
```

2. 当前靶机管理逻辑？

是根据所生成的flag 自己通过脚本写入靶机下？后续是否考虑新增靶机时填写ssh等信息，直接管理端定时更新靶机flag。

3.  前端小问题

靶机编辑框有点问题

**Comment by wuhan005** [comment]
感谢您的反馈~ (*^▽^*)

1. 请检查您 MySQL 表的字符集是否为 UTF8。
2. 目前的逻辑是平台生成 Flag 后导出，再手动编写脚本每轮更新靶机 Flag。考虑到这样有些繁琐，之后会尽快加入每轮结束后直接从平台通过 SSH 更新靶机 Flag。
3. 了解，将尽快更新修复，感谢反馈。

**Comment by XuCcc** [comment]
谢谢你 你很美  ~
