### ISSUE TITLE
前端没有那种飞机大战效果吗

### ISSUE THREAD

**Issue by PolarPeak** [vidar-team/Cardinal#43]
求一个炫酷的大屏效果

**Comment by wuhan005** [comment]
大屏3D的飞机大战效果是我另外用Unity写的，目前还未开源。
平台下一个版本计划会加WebHook功能，然后就可以很方便地接入类似这样的3D大屏，届时飞机大战的大屏应该会放出测试版给大家使用。

**Comment by wuhan005** [comment]
现已开源~

https://github.com/wuhan005/Asteroid
