### ISSUE TITLE
前端问题

### ISSUE THREAD

**Issue by xuxinhen** [vidar-team/Cardinal#47]
你好，请问3D大屏是没有加上去吗？页面地址是多少？

**Comment by xuxinhen** [comment]
> 你好，请问前端是没有加上去吗？端口号是多少

**Comment by wuhan005** [comment]
https://github.com/wuhan005/Asteroid
3D 大屏是另一个项目，是用 Unity 开发。Cardinal 目前是通过 Webhook 的形式进行接入。
