### ISSUE TITLE
大屏问题

### ISSUE THREAD

**Issue by YOunGWebER** [vidar-team/Cardinal#52]
**Environment**:

  - Go Version: 
![image](https://user-images.githubusercontent.com/49063068/86429186-60926a00-bd21-11ea-99c6-fadf6881ce80.png)

  - Operating System:
![image](https://user-images.githubusercontent.com/49063068/86429196-66884b00-bd21-11ea-957d-f01571f3f1a5.png)

unity version:
![image](https://user-images.githubusercontent.com/49063068/86429217-7b64de80-bd21-11ea-8795-97c3cc82b489.png)

**What happened?**
![image](https://user-images.githubusercontent.com/49063068/86429266-a18a7e80-bd21-11ea-80e6-f071c995f997.png)
导入地址后，点击播放报错
**What did you expect to happen?**

**How to reproduce your issue**

**Any associated stack traces or error logs**
![image](https://user-images.githubusercontent.com/49063068/86429319-c1ba3d80-bd21-11ea-934f-604e9763dda9.png)

**Comment by wuhan005** [comment]
正常情况下，是直接在 Unity 的面板上改`url`的，而不是改代码。
您那边是 clone 的最新的 https://github.com/wuhan005/Asteroid 吗？
还有 Unity 的报错信息能发一下吗？

**Comment by YOunGWebER** [comment]
是最新的
![image](https://user-images.githubusercontent.com/49063068/86430071-e0213880-bd23-11ea-98a2-37831370c179.png)
不好意思，我找不到unity面板上改url的地方，第一次接触unity，能不能截图教一下呀

**Comment by wuhan005** [comment]
![](https://user-images.githubusercontent.com/49063068/86429319-c1ba3d80-bd21-11ea-934f-604e9763dda9.png)
就这一张图，Unity 一打开就提示这样的错误吗？正常的话是在这个面板改的。

**Comment by YOunGWebER** [comment]
对，一打开就是这样错误
![image](https://user-images.githubusercontent.com/49063068/86430508-0d221b00-bd25-11ea-82e0-6a17ef294f33.png)
尝试重新打开新文件也是这样

**Comment by YOunGWebER** [comment]
![image](https://user-images.githubusercontent.com/49063068/86430527-2034eb00-bd25-11ea-8761-224eec14fa36.png)

**Comment by YOunGWebER** [comment]
1

**Comment by YOunGWebER** [comment]
> **Environment**:
> 
> * Go Version:
>   ![image](https://user-images.githubusercontent.com/49063068/86429186-60926a00-bd21-11ea-99c6-fadf6881ce80.png)
> * Operating System:
>   ![image](https://user-images.githubusercontent.com/49063068/86429196-66884b00-bd21-11ea-957d-f01571f3f1a5.png)
> 
> unity version:
> ![image](https://user-images.githubusercontent.com/49063068/86429217-7b64de80-bd21-11ea-8795-97c3cc82b489.png)
> 
> **What happened?**
> ![image](https://user-images.githubusercontent.com/49063068/86429266-a18a7e80-bd21-11ea-80e6-f071c995f997.png)
> 导入地址后，点击播放报错
> **What did you expect to happen?**
> 
> **How to reproduce your issue**
> 
> **Any associated stack traces or error logs**
> ![image](https://user-images.githubusercontent.com/49063068/86429319-c1ba3d80-bd21-11ea-934f-604e9763dda9.png)
