### ISSUE TITLE
大屏

### ISSUE THREAD

**Issue by YOunGWebER** [vidar-team/Cardinal#53]
**Environment**:

  - Go Version: 
![image](https://user-images.githubusercontent.com/49063068/86429186-60926a00-bd21-11ea-99c6-fadf6881ce80.png)

  - Operating System:
![image](https://user-images.githubusercontent.com/49063068/86429196-66884b00-bd21-11ea-957d-f01571f3f1a5.png)

unity version:
![image](https://user-images.githubusercontent.com/49063068/86429217-7b64de80-bd21-11ea-8795-97c3cc82b489.png)

**What happened?**
![image](https://user-images.githubusercontent.com/49063068/86429266-a18a7e80-bd21-11ea-80e6-f071c995f997.png)
导入地址后，点击播放报错
**What did you expect to happen?**

**How to reproduce your issue**

**Any associated stack traces or error logs**
![image](https://user-images.githubusercontent.com/49063068/86429319-c1ba3d80-bd21-11ea-934f-604e9763dda9.png)

**Comment by YOunGWebER** [comment]
不好意思，误关了

**Comment by wuhan005** [comment]
[v1.0](https://github.com/wuhan005/Asteroid/releases/tag/v1.0) 版本已经有各平台的 Release，无需再自己手动编译。
