### ISSUE TITLE
求助师傅，陨石彩蛋正常，但是不显示队伍信息

### ISSUE THREAD

**Issue by 1476110462** [vidar-team/Cardinal#57]
**运行环境 Environment**:

  - Go 版本 / Go Version:  
    
  - 操作系统 / Operating System: 

**发生了什么？/ What happened?**

**您的预期结果是什么？/ What did you expect to happen?**

**如何复现您的问题？/ How to reproduce your issue?**

**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**

求助师傅，陨石彩蛋正常，但是不显示队伍信息

**Comment by wuhan005** [comment]
请按照 issue 模板填写，详细描述您遇到的问题。

**Comment by hundan2020** [comment]
调整 `Asteroid_Data\StreamingAssets\asteroid.ini`中的`[scene]`配置

**Comment by 1476110462** [comment]
> 调整 `Asteroid_Data\StreamingAssets\asteroid.ini`中的`[scene]`配置

![图片](https://user-images.githubusercontent.com/47727764/89019021-444d1180-d34f-11ea-9018-f90fd326c150.png)
emmmmm,我不知道那里，麻烦师傅帮忙看看

**Comment by 1476110462** [comment]
> 请按照 issue 模板填写，详细描述您遇到的问题。

运行环境 Environment:

    Go 版本 / Go Version:

    操作系统 / Operating System:   ubuntu18.04 lts      gnome3

发生了什么？/ 陨石彩蛋正常，但是不显示队伍信息

您的预期结果是什么？/ 希望可以显示队伍的信息，还有攻击效果

如何复现您的问题？/ How to reproduce your issue?

额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs

**Comment by wuhan005** [comment]
> > 调整 `Asteroid_Data\StreamingAssets\asteroid.ini`中的`[scene]`配置
> 
> ![图片](https://user-images.githubusercontent.com/47727764/89019021-444d1180-d34f-11ea-9018-f90fd326c150.png)
> emmmmm,我不知道那里，麻烦师傅帮忙看看

你上面配置这里是没问题的，陨石彩蛋正常说明已经成功连上了。师傅截图看一下后台的队伍信息。

**Comment by 1476110462** [comment]
> > > 调整 `Asteroid_Data\StreamingAssets\asteroid.ini`中的`[scene]`配置
> > 
> > 
> > ![图片](https://user-images.githubusercontent.com/47727764/89019021-444d1180-d34f-11ea-9018-f90fd326c150.png)
> > emmmmm,我不知道那里，麻烦师傅帮忙看看
> 
> 你上面配置这里是没问题的，陨石彩蛋正常说明已经成功连上了。师傅截图看一下后台的队伍信息。

![图片](https://user-images.githubusercontent.com/47727764/89025973-6bf5a700-d35a-11ea-8048-e596fbfd8ef4.png)

**Comment by wuhan005** [comment]
之前发了 v0.6.1，刚才一看居然是 Draft Release，现在好了。😅
师傅到 Release 里下载 [v0.6.1](https://github.com/vidar-team/Cardinal/releases/tag/v0.6.1) 版本安装试一下。

**Comment by 1476110462** [comment]
> 之前发了 v0.6.1，刚才一看居然是 Draft Release，现在好了。sweat_smile
> 师傅到 Release 里下载 [v0.6.1](https://github.com/vidar-team/Cardinal/releases/tag/v0.6.1) 版本安装试一下。

好嘞师傅，我马上试试，麻烦您了，嘿嘿

**Comment by 1476110462** [comment]
> 之前发了 v0.6.1，刚才一看居然是 Draft Release，现在好了。sweat_smile
> 师傅到 Release 里下载 [v0.6.1](https://github.com/vidar-team/Cardinal/releases/tag/v0.6.1) 版本安装试一下。

解决了，师傅，谢谢您
