### ISSUE TITLE
使用遇到问题

### ISSUE THREAD

**Issue by Gu-f** [vidar-team/Cardinal#67]
我再进行从镜像部署题目的时候点击添加，一直提示Resource Not Found!。这是怎么回事呢

**Comment by wuhan005** [comment]
抱歉，这个是还在开发中的功能，v0.7.0 版本发布时未删除。目前仅支持手动添加外部部署的靶机。
v0.7.1 已经删除该选项，避免误导。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Gu-f <notifications@github.com&gt;
发送时间: 2020年8月28日 20:22
收件人: vidar-team/Cardinal <Cardinal@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[vidar-team/Cardinal] 使用遇到问题 (#67)





 
我再进行从镜像部署题目的时候点击添加，一直提示Resource Not Found!。这是怎么回事呢

**Comment by Gu-f** [comment]
谢谢
