### ISSUE TITLE
添加docker 靶机 显示 Resource Not Found!

### ISSUE THREAD

**Issue by myxss** [vidar-team/Cardinal#68]
**运行环境 Environment**:

  - Go 版本 / Go Version:  
    
  - 操作系统 / Operating System: 

**发生了什么？/ What happened?**

**您的预期结果是什么？/ What did you expect to happen?**

**如何复现您的问题？/ How to reproduce your issue?**

**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**

**Comment by wuhan005** [comment]
同 #67

**Comment by myxss** [comment]
好的，感谢
