### ISSUE TITLE
题目管理设为哦是否可见，不能将题目在选手端显示出来

### ISSUE THREAD

**Issue by CaiH123** [vidar-team/Cardinal#72]
确定

**运行环境 Environment**:

  - Go 版本 / Go Version:  
    
  - 操作系统 / Operating System: kali

**发生了什么？/ What happened?**
题目管理->设置可见->"您确定要设置该题目状态为公开吗？"选择确定，但是"是否可见"仍然是false，且题目不能在选手端显示出来
**您的预期结果是什么？/ What did you expect to happen?**
希望题目管理->设置可见->"您确定要设置该题目状态为公开吗？"选择确定，但是"是否可见"变成true，且题目能在选手端显示出来
**如何复现您的问题？/ How to reproduce your issue?**
题目管理->设置可见->"您确定要设置该题目状态为公开吗？"选择确定
**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**

**Comment by wuhan005** [comment]
相关题目下是否已经添加了靶机？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 菜鸡CaiH <notifications@github.com&gt;
发送时间: 2020年9月17日 21:09
收件人: vidar-team/Cardinal <Cardinal@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[vidar-team/Cardinal] 题目管理设为哦是否可见，不能将题目在选手端显示出来 (#72)





 确定 
运行环境 Environment:
  
 
Go 版本 / Go Version:  
 

 
操作系统 / Operating System: kali
 
 
发生了什么？/ What happened?
 题目管理-&gt;设置可见-&gt;"您确定要设置该题目状态为公开吗？"选择确定，但是"是否可见"仍然是false，且题目不能在选手端显示出来
 您的预期结果是什么？/ What did you expect to happen?
 希望题目管理-&gt;设置可见-&gt;"您确定要设置该题目状态为公开吗？"选择确定，但是"是否可见"变成true，且题目能在选手端显示出来
 如何复现您的问题？/ How to reproduce your issue?
 题目管理-&gt;设置可见-&gt;"您确定要设置该题目状态为公开吗？"选择确定
 额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs

**Comment by CaiH123** [comment]
可以了，谢谢您
