### ISSUE TITLE
请问作为选手方如何获取flag

### ISSUE THREAD

**Issue by CaiH123** [vidar-team/Cardinal#73]
请问作为比赛选手getshell之后如何才能获取对手靶机的flag，是发送那个POST数据包吗，不是很能理解这个数据包的内容，这和getshell之间的关系是什么
POST /flag
Header
Content-Type: application/json
Authorization: 3bbf804b505b3665bf048ee6253e7cf6
Body
{"flag": "your_flag_here"}
curl -X POST http://192.168.1.177:19999/api/flag -H "Authorization: 3bbf804b505b3665bf048ee6253e7cf6" -d "{ \"flag\": \"your_flag_here\" }"

**Comment by wuhan005** [comment]
AWD 拿到对方靶机上的shell之后，flag一般会放在靶机的 /flag 下，读取这个文件的内容，POST发送到平台提交flag的接口，即攻击成功。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 菜鸡CaiH <notifications@github.com&gt;
发送时间: 2020年9月17日 21:52
收件人: vidar-team/Cardinal <Cardinal@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[vidar-team/Cardinal] 请问作为选手方如何获取flag (#73)





 
请问作为比赛选手getshell之后如何才能获取对手靶机的flag，是发送那个POST数据包吗，不是很能理解这个数据包的内容，这和getshell之间的关系是什么
 POST /flag
 Header
 Content-Type: application/json
 Authorization: 3bbf804b505b3665bf048ee6253e7cf6
 Body
 {"flag": "your_flag_here"}
 curl -X POST http://192.168.1.177:19999/api/flag -H "Authorization: 3bbf804b505b3665bf048ee6253e7cf6" -d "{ "flag": "your_flag_here" }"

**Comment by CaiH123** [comment]
我还是有点糊涂，请问如何将flag放在靶机的 /flag 下，这个flag和flag管理里面的flag的区别是什么

**Comment by wuhan005** [comment]
Cardinal 只是 AWD 比赛平台，选手的靶机是另外单独维护的，常见的是部署在一个个 Docker 容器里。
比赛主办方定时更新容器根目录下的 flag 文件内容。当选手拿到对方容器的 shell 之后，可以执行例如 `cat /flag` 命令来获取 flag 文件的内容。再将 flag 的内容通过平台接口提交，即 POST /api/flag 的接口。提交成功后即可得分。


因此每轮的 flag 要提前在 Cardinal 中生成，然后每轮定时更新至靶机内。更新 flag 的操作可以额外写脚本更新或者使用 Cardinal 的自动更新 flag 功能，其原理是 SSH 连接上靶机后修改 /flag 文件内容。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 菜鸡CaiH <notifications@github.com&gt;
发送时间: 2020年9月17日 22:14
收件人: vidar-team/Cardinal <Cardinal@noreply.github.com&gt;
抄送: E99p1ant <524306184@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[vidar-team/Cardinal] 请问作为选手方如何获取flag (#73)





 
我还是有点糊涂，请问如何将flag放在靶机的 /flag 下，这个flag和flag管理里面的flag的区别是什么

**Comment by CaiH123** [comment]
明白了，谢谢您
