### ISSUE TITLE
Docker部署脚本找不到

### ISSUE THREAD

**Issue by 1925473403** [vidar-team/Cardinal#74]
开发者您好，我在按照您的文档部署docker执行

> curl https://sh.cardinal.ink | bash

时得到的却是一个

Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

请问这时候该怎么解决呢XD

**Comment by wuhan005** [comment]
经排查发现是 Netfliy 路由重写的问题，现已修复。
感谢您的反馈！

**Comment by wuhan005** [comment]
请执行：`curl https://sh.cardinal.ink/ | sh`

**Comment by 1925473403** [comment]
可以了：P
