### ISSUE TITLE
Cardinal/src 目录找不到

### ISSUE THREAD

**Issue by ybm911** [vidar-team/Cardinal#75]
**运行环境 Environment**:

  - Go 版本 / Go Version:  
    
  - 操作系统 / Operating System: 

**发生了什么？/ What happened?**

**您的预期结果是什么？/ What did you expect to happen?**

**如何复现您的问题？/ How to reproduce your issue?**

**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**

**Comment by wuhan005** [comment]
目前是重构之后的代码，README 还未更新。
手动编译时忽略掉`cd Cardinal/src`直接执行`go build -o Cardinal`即可。

**Comment by wuhan005** [comment]
Fixed in https://github.com/vidar-team/Cardinal/commit/84e54b9dca013aeeec6b85d5e28a62c29942bbf8

**Comment by wuhan005** [comment]
Fixed in https://github.com/vidar-team/Cardinal/commit/84e54b9dca013aeeec6b85d5e28a62c29942bbf8
