### ISSUE TITLE
管理员登录失败

### ISSUE THREAD

**Issue by ybm911** [vidar-team/Cardinal#77]
**运行环境 Environment**:

  - Go 版本 / Go Version:   go version go1.15 linux/amd64
    
  - 操作系统 / Operating System: centos 7.x
**发生了什么？/ What happened?**
无论我怎么重新来过，都登陆不了管理员账号。管理员账号就只在第一次配置的时候让我设置过，但是当我后面登陆的时候，却显示认证错误，我想当确信我输入的事正确的。
请问怎么才能重新设置管理员密码（我删除了 conf/  也没用）

**您的预期结果是什么？/ What did you expect to happen?**

**如何复现您的问题？/ How to reproduce your issue?**

**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**

**Comment by wuhan005** [comment]
请问是在哪里登录的？网页URL是什么？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Elli0t <notifications@github.com&gt;
发送时间: 2020年9月19日 17:27
收件人: vidar-team/Cardinal <Cardinal@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[vidar-team/Cardinal] 管理员登录失败 (#77)





 
运行环境 Environment:
  
 
Go 版本 / Go Version:   go version go1.15 linux/amd64
 

 
操作系统 / Operating System: centos 7.x
 发生了什么？/ What happened?
 无论我怎么重新来过，都登陆不了管理员账号。管理员账号就只在第一次配置的时候让我设置过，但是当我后面登陆的时候，却显示认证错误，我想当确信我输入的事正确的。
 请问怎么才能重新设置管理员密码（我删除了 conf/  也没用）
 
 
您的预期结果是什么？/ What did you expect to happen?
 
如何复现您的问题？/ How to reproduce your issue?
 
额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs

**Comment by ybm911** [comment]
您好，我是在 127.0.0.1:19999/manager/#/login

**Comment by ybm911** [comment]
> 请问是在哪里登录的？网页URL是什么？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Elli0t <notifications@github.com&gt; 发送时间: 2020年9月19日 17:27 收件人: vidar-team/Cardinal <Cardinal@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[vidar-team/Cardinal] 管理员登录失败 (#77) 运行环境 Environment: Go 版本 / Go Version: go version go1.15 linux/amd64 操作系统 / Operating System: centos 7.x 发生了什么？/ What happened? 无论我怎么重新来过，都登陆不了管理员账号。管理员账号就只在第一次配置的时候让我设置过，但是当我后面登陆的时候，却显示认证错误，我想当确信我输入的事正确的。 请问怎么才能重新设置管理员密码（我删除了 conf/ 也没用） 您的预期结果是什么？/ What did you expect to happen? 如何复现您的问题？/ How to reproduce your issue? 额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wuhan005** [comment]
嗯 请尝试将conf文件夹删除后，**再删除数据库**重新创建。

只删除conf文件夹的话，重新生成的配置文件salt更新，就登录不上了。

**Comment by ybm911** [comment]
嗯，非常感谢🙏。竟然忘了删除数据库文件
