### ISSUE TITLE
如何更新靶机的flag

### ISSUE THREAD

**Issue by CaiH123** [vidar-team/Cardinal#78]
请问如何更新靶机的flag，应该在靶机上面添加flag文件夹吗还是如何进行操作

**Comment by wuhan005** [comment]
更新 flag 的操作可以额外写脚本更新或者使用 Cardinal 的自动更新 flag 功能。

**Comment by CaiH123** [comment]
我使用了该功能，但是并未在靶机上看到flag这个文件，难道需要自己新建flag这个文件吗，还有请问challenge里面更新flag的命令是什么------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;E99p1ant&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月19日(星期六) 晚上10:13
收件人:&nbsp;&quot;vidar-team/Cardinal&quot;<Cardinal@noreply.github.com&gt;;
抄送:&nbsp;&quot;菜鸡CaiH&quot;<2044329825@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vidar-team/Cardinal] 如何更新靶机的flag (#78)

**Comment by wuhan005** [comment]
首先要生成 Flag，然后在每轮结束后就会去自动创建 Flag 文件。可以点击`测试 SSH 连接`来确保平台能连上靶机。

Challenge 里更新 Flag 的命令是手动更新该靶机下的 Flag。

**Comment by CaiH123** [comment]
请问为何点击生成flag之后，在靶机中并未看到生成的flag文件，谢谢您------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;E99p1ant&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月19日(星期六) 晚上10:36
收件人:&nbsp;&quot;vidar-team/Cardinal&quot;<Cardinal@noreply.github.com&gt;;
抄送:&nbsp;&quot;菜鸡CaiH&quot;<2044329825@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vidar-team/Cardinal] 如何更新靶机的flag (#78)

**Comment by CaiH123** [comment]
已解决，谢谢您
