### ISSUE TITLE
安装Asteroid出现错误

### ISSUE THREAD

**Issue by CaiH123** [vidar-team/Cardinal#82]
**运行环境 Environment**:

  - Go 版本 / Go Version:  
    
  - 操作系统 / Operating System:  kali

**发生了什么？/ What happened?**
安装Asteroid出现错误，最后运行./Asteroid时报错

**您的预期结果是什么？/ What did you expect to happen?**
可以成功运行
**如何复现您的问题？/ How to reproduce your issue?**
按照官网教程来，最后运行./Asteroid运行错误
**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**
报错信息如下
Set current directory to /home/build/StandaloneLinux64
Found path: /home/build/StandaloneLinux64/Asteroid
Mono path[0] = '/home/build/StandaloneLinux64/Asteroid_Data/Managed'
Mono config path = '/home/build/StandaloneLinux64/Asteroid_Data/MonoBleedingEdge/etc'
Preloaded 'ScreenSelector.so'
Display 0 '0': 1280x720 (primary device).
Logging to /root/.config/unity3d/Editor/Player.log
INTEL-MESA: warning: Haswell Vulkan support is incomplete
INTEL-MESA: warning: Haswell Vulkan support is incomplete
vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
XIO:  fatal IO error 62 (Timer expired) on X server "localhost:10.0"
      after 269 requests (268 known processed) with 45 events remaining.

**Comment by wuhan005** [comment]
> INTEL-MESA: warning: Haswell Vulkan support is incomplete

请尝试更换其他的操作系统，Kali 看起来是不完整支持 Vulkan。
