### ISSUE TITLE
请问如果使用docker作为靶场，那怎么向docker里面添加flag

### ISSUE THREAD

**Issue by hxy-hxy** [vidar-team/Cardinal#84]
请问如果使用docker作为靶场，那怎么向docker里面添加flag，题目的flag ssh的账号密码端口分别应该填什么，是dcoker所在主机上面的ssh信息吗,真的谢谢您，感激不尽

**Comment by wuhan005** [comment]
现在平台支持在每轮时自动更新 Flag，原理是平台 SSH 连上后执行命令替换 flag 文件。因此 flag ssh 账号密码端口填写容器的 SSH 信息，账号一般为 root。

配置前请先确认容器可以使用 root 账号 SSH 登录。

**Comment by ttttyy123** [comment]
也就是说我们使用的docker需要开放22端口吗

**Comment by wuhan005** [comment]
嗯对，题目需要开放或映射 22 端口，让选手能 SSH 登录上靶机。

**Comment by teawaterwu** [comment]
> 现在平台支持在每轮时自动更新 Flag，原理是平台 SSH 连上后执行命令替换 flag 文件。因此 flag ssh 账号密码端口填写容器的 SSH 信息，账号一般为 root。
> 
> 配置前请先确认容器可以使用 root 账号 SSH 登录。

有一个问题，如果参赛者登录靶机后修改了root密码，平台就无法使用ssh更新flag值，可是参赛者修改root密码是常见的防御性操作，请问如何解决这个问题？

**Comment by wuhan005** [comment]
> > 现在平台支持在每轮时自动更新 Flag，原理是平台 SSH 连上后执行命令替换 flag 文件。因此 flag ssh 账号密码端口填写容器的 SSH 信息，账号一般为 root。
> > 配置前请先确认容器可以使用 root 账号 SSH 登录。
> 
> 有一个问题，如果参赛者登录靶机后修改了root密码，平台就无法使用ssh更新flag值，可是参赛者修改root密码是常见的防御性操作，请问如何解决这个问题？

传统 AWD 里是不会给参赛者 root 权限账号的，只会给低权账号；提权以及修改 root 密码都是不允许的。如果参赛者能接触到 root，那他完全不需要改密码，直接定时删 /flag 不就好了。平台就算能更新 flag 也没用。

**Comment by teawaterwu** [comment]
> > > 现在平台支持在每轮时自动更新 Flag，原理是平台 SSH 连上后执行命令替换 flag 文件。因此 flag ssh 账号密码端口填写容器的 SSH 信息，账号一般为 root。
> > > 配置前请先确认容器可以使用 root 账号 SSH 登录。
> > 
> > 
> > 有一个问题，如果参赛者登录靶机后修改了root密码，平台就无法使用ssh更新flag值，可是参赛者修改root密码是常见的防御性操作，请问如何解决这个问题？
> 
> 传统 AWD 里是不会给参赛者 root 权限账号的，只会给低权账号；提权以及修改 root 密码都是不允许的。如果参赛者能接触到 root，那他完全不需要改密码，直接定时删 /flag 不就好了。平台就算能更新 flag 也没用。

感谢回复

**Comment by yanhuanyu** [comment]
用docker搭建的managers密码是多少 = =

**Comment by wuhan005** [comment]
使用 Docker 部署，manager 密码在 Docker 容器 logs 里都可以查看

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yanhuanyu <notifications@github.com&gt;
发送时间: 2020年12月20日 15:07
收件人: vidar-team/Cardinal <Cardinal@noreply.github.com&gt;
抄送: E99p1ant <524306184@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[vidar-team/Cardinal] 请问如果使用docker作为靶场，那怎么向docker里面添加flag (#84)
