### ISSUE TITLE
安装指南里不提供一下创库脚本吗？

### ISSUE THREAD

**Issue by bigBestWay** [vidar-team/Cardinal#85]
**运行环境 Environment**:

  - Go 版本 / Go Version:   
    
  - 操作系统 / Operating System:  ubuntu 1604

**发生了什么？/ What happened?**
使用Release安装，没有创库脚本，根本不知道表结构，提示
2020/10/10 16:53:35 加载配置文件成功
2020/10/10 16:53:35 Error 1049: Unknown database 'cardinal'

**您的预期结果是什么？/ What did you expect to happen?**
按照指南能顺畅完成安装

**如何复现您的问题？/ How to reproduce your issue?**

**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**

**Comment by wuhan005** [comment]
数据库的表是自动创建的，不需要创库脚本。

请问您的配置文件是根据安装时自动生成的吗？

**Comment by bigBestWay** [comment]
> 数据库的表是自动创建的，不需要创库脚本。
> 
> 请问您的配置文件是根据安装时自动生成的吗？

是的，按提示填写。
我手动执行SQL
CREATE DATABASE  `cardinal` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
问题解决，这个脚本应该集成在安装包里
