### ISSUE TITLE
账号问题

### ISSUE THREAD

**Issue by tianshu666** [vidar-team/Cardinal#93]
**运行环境 Environment**:
    
  - 操作系统 / Operating System: 

**发生了什么？/ What happened?**

**您的预期结果是什么？/ What did you expect to happen?**

**如何复现您的问题？/ How to reproduce your issue?**

**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**

设定的管理员账号密码无法登录管理端

**Comment by wuhan005** [comment]
请提供更详细的问题描述。（截图、终端日志等）
