### ISSUE TITLE
其它的什么都能实现，但就是不能更新靶机flag，是root权限

### ISSUE THREAD

**Issue by luoqichen** [vidar-team/Cardinal#94]

**Comment by luoqichen** [comment]
其它的什么都能实现，但就是不能更新靶机flag，是root权限

**Comment by luoqichen** [comment]
文档的dockerfile中一开始设置的是flag.txt，开启后几个回合都没有改变flag，就把他变成了flag，但也没有什么改变

**Comment by wuhan005** [comment]
请提供更详细的信息。（比如添加靶机的窗口截图，报错信息等）。

也可尝试点击靶机管理页面的`测试 SSH 连接`按钮测试连接。

**Comment by luoqichen** [comment]
![3](https://user-images.githubusercontent.com/50563536/101454593-2f6f3300-396c-11eb-8fa2-bedfe05e5720.PNG)
![1](https://user-images.githubusercontent.com/50563536/101454597-3138f680-396c-11eb-9852-0cd54118f997.PNG)
![2](https://user-images.githubusercontent.com/50563536/101454600-3302ba00-396c-11eb-863c-074960f78bb9.PNG)

**Comment by luoqichen** [comment]
ssh测试是可以实现的，输入命令是有回显的

**Comment by wuhan005** [comment]
嗯 题目信息窗口截图一下，看一下更新 Flag 的命令是否正确。

**Comment by luoqichen** [comment]
可以了，谢谢，没有注意到这一块

**Comment by wuhan005** [comment]
Flag 命令是不是写成`cat /flag`了😆

**Comment by luoqichen** [comment]
echo {{FLAG}} > /flga 写反了 😆
还有个小问题，就是checkdown是怎么设置的，我删了其中一个靶机的源码没有被算宕机

**Comment by wuhan005** [comment]
Check 是需要额外维护一个脚本来检测服务是否可用。若检测到选手服务宕机，则发送消息给平台接口将选手靶机状态设置为 Down。

可以参考文档：https://cardinal.ink/question/how-about-check.html

**Comment by luoqichen** [comment]
好的，谢谢，你这个项目真棒，我们学校想要用来打比赛，需要哪些程序才能使用这个呢
😄

**Comment by wuhan005** [comment]
直接下载二进制用就行，没啥限制。
（最好能帮忙宣传下，感谢 ♪(･ω･)ﾉ
