### ISSUE TITLE
怎么弄管理员账号，突然间就忘记了

### ISSUE THREAD

**Issue by luoqichen** [vidar-team/Cardinal#99]
**运行环境 Environment**:
    
  - 操作系统 / Operating System: 

**发生了什么？/ What happened?**

**您的预期结果是什么？/ What did you expect to happen?**

**如何复现您的问题？/ How to reproduce your issue?**

**额外的补充信息（堆栈信息、错误日志等）/ Any associated stack traces or error logs**

**Comment by wuhan005** [comment]
如果忘记管理员账号，请清空数据库中`managers`表的内容，或者直接删除`managers`表，并重启 Cardinal。
重启后会自动建表，并提示输入管理员账号密码。
